config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  root :to => 'pages#home'

  # get 'blogs' => 'blogs#index'
  #
  # get 'blogs/new' => 'blogs#new'
  #
  # post 'blogs' => 'blogs#create'
  #
  # get 'blogs/:id' => 'blogs#show'
  #
  # get 'blogs/:id/edit' => 'blogs#edit'
  #
  # patch 'blogs/:id' => 'blogs#update'
  #
  # delete 'blogs/:id' => 'blogs#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #/welcome in website refers to pages_controller.rb

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update_attributes(blog_params)
    redirect_to blog_path(@blog)
  end

  def create
    @blog = Blog.create(blog_params)
        redirect_to blogs_path
    end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:name, :framework, :message)
    end
#this is essential for the create to work but the delete and edit routes then are mad

  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    puts 'hallo'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <title></title>
  </head>
  <body class="bg-red-700">
    <div class="px-8 py-12">
     <div class="md:flex">
      <div class="md:flex-shrink-0">
        <img class="rounded-lg md:w-56" src="https://i.imgur.com/KXDrpBf.giff" alt="Unexpected Reboot">
      </div>
      <div class="mt-4 md:mt-0 md:ml-6">
        <div class="uppercase tracking-wide text-sm text-black-900 font-bold">Have you tried turning it off and on again?</div>
        <h4 class="block mt-1 text-lg leading-tight font-semibold text-gray-700">Edit This Blog Post</h4>
        <center>
          <h3 class="mt-2 text-gray-900">
            <%= form_for @blog do |f| %>
              <%= f.label :name %><br />
              <%= f.text_area :name %><br />
              <%= f.label :framework %><br />
              <%= f.text_area :framework, col:"50", row:"30" %><br />
              <%= f.label :message %><br />
              <%= f.text_area :message, cols:"50", row:"30" %><br />
              <%= f.submit value="Changing a few things" %><br />
              <br />
            <p class="text-gray-700 hover:underline">
              <%= link_to 'Nevermind, back to the Blogs', "/blogs" %>
            </p>
            <% end %>
          </h3>
        </center>
      </div>
    </div>

  </div>
</body>
</html>

<!-- <h1>Blogs#edit</h1>
<p>Find me in app/views/blogs/edit.html.erb</p> -->

app/views/blogs/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <title></title>
  </head>
  <body>
<body class="bg-red-700">
  <div class="px-8 py-12">
   <div class="md:flex">
    <div class="md:flex-shrink-0">
      <img class="rounded-lg md:w-56" src="https://i.imgur.com/ZPL7kUB.gif" alt="Moss Throw Computer">
    </div>
    <div class="mt-4 md:mt-0 md:ml-6">
      <div class="uppercase tracking-wide text-sm text-black-900 font-bold">Coder's Block: How Many things can I break with one character?</div>
      <h4 class="block mt-1 text-lg leading-tight font-semibold text-gray-700">Confessions of a Developing Developer</h4>
<br />
<center>
  <p class="text-gray-700 hover:underline"
    <%= link_to 'New Blog', "blogs/new" %>
  </p>

  <div class="p12">
      <% @blogs.each do |blog| %>
      <div class="blog bg-white rounded-lg overflow-hidden shadow-xl mt-4 md:mt-0 md:ml-6 box-border p-4 border-4 border-gray-400 bg-gray-200 text-left w-full">
        <h2 class="text-lg text-gray-600">Title:</h2>
          <h5 class="text-gray-900"><%= blog.name %></h5><br />
            <hr>
              <h2 class="text-lg text-gray-600">Framework(s):</h2>
                <p class="framework"><%= blog.framework %></p><br />
                  <hr>
                    <p class="message"><%= blog.message %></p><br />
                      <hr>
                        <p class="time text-lg text-gray-600"><%= blog.created_at %></p><br />
                            <p class="text-gray-700 hover:underline">
                              <%= link_to "Bye Blog", blog_path(blog), :method => :delete%>
                            </p>
                            <p class="text-gray-700 hover:underline">
                              <%= link_to 'Edit Blog', edit_blog_path(blog) %>
                            </p></span>

    </div>
  </center>
 </div>
<% end %>

</body>
</html>

app/views/blogs/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <title></title>
  </head>
  <body class="bg-red-700">
    <div class="px-8 py-12">
     <div class="md:flex">
      <div class="md:flex-shrink-0">
        <img class="rounded-lg md:w-56" src="https://i.imgur.com/GUxN3O1.gif" alt="Moss Fire">
      </div>
      <div class="mt-4 md:mt-0 md:ml-6">
        <div class="uppercase tracking-wide text-sm text-black-900 font-bold">What's Wrong this Time?</div>
        <h4 class="block mt-1 text-lg leading-tight font-semibold text-gray-700">Make a New Post</h4>
        <center>
          <h3 class="mt-2 text-gray-900">
          <%= form_for(@blog) do |f| %>
            <div class="field">
              <%= f.label :name %><br />
              <%= f.text_area :name %><br />
              <%= f.label :framework %><br />
              <%= f.text_area :framework, col:"50", row:"30" %><br />
              <%= f.label :message %><br />
              <%= f.text_area :message, col:"50", row:"30" %><br />
            </div><br />
            <div class="actions">
              <%= f.submit "Bloggin' my Bugs away" %>
            </div>
              <p class="text-gray-700 hover:underline"><br />
                <%= link_to 'Let me rethink that... back to the Blogs', "/blogs" %>
              </p>
            </center>
          <% end %>

</body>
</html>
<!-- <h1>Blogs#new</h1>
<p>Find me in app/views/blogs/new.html.erb</p> -->

app/views/blogs/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <title></title>
  </head>
  <body class="bg-red-700">
    <div class="px-8 py-12">
     <div class="md:flex">
      <div class="md:flex-shrink-0">
        <img class="rounded-lg md:w-56" src="https://i.imgur.com/7b9MeHY.gif" alt="stare in horror">
      </div>
      <div class="mt-4 md:mt-0 md:ml-6">
        <div class="uppercase tracking-wide text-sm text-black-900 font-bold">What's Wrong this Time?</div>
        <h4 class="block mt-1 text-lg leading-tight font-semibold text-gray-700">Make a New Post</h4>
        <center>



<h3 class="mt-2 text-gray-900">Title:</h3>
  <p class="name"><%=@blog.name %></p>

<h3 class="mt-2 text-gray-900"Framework(s):</h3>
  <p class="framework"><%=  @blog.framework %></p>
  <p class="message"><%= @blog.message %></p>
<p class="time"><%= @blog.created_at %></p>

<%= link_to 'All Blog Post', "/blogs" %>

</center>
</body>
</html>
<!-- <h1>Blogs#show</h1>
<p>Find me in app/views/blogs/show.html.erb</p> -->

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <title></title>
  </head>
  <body class="bg-red-800">

<div class="md:flex bg-white rounded-lg p-6">
  <a
    href="https://unangellily.github.io/portfolio/">
      <img
        class="h-16 w-16 md:h-24 md:w-24 rounded-full mx-auto md:mx-0 md:mr-6"
        src="https://unangellily.github.io/portfolio/public/images/lilyprofilepicture.jpeg">
  </a>
  <div class="text-center md:text-left">
    <h2 class="text-lg text-red-600">Lily J Herreria</h2>
    <div class="text-red-800">Software Enginner || Fullstack Developer</div>
    <div class="text-gray-600">Hello my name is Lily, I'm a Developer</div>
    <div class="text-gray-600">The best traits I have all come from f#$%king up</div>
    <br />
      <center>
        <p>
          You can't get better by being perfect, and we all start off somewhere,<br />
           so why not reflect on my f$%^ ups for entertainment value?</p><br />
            <p class="text-red-900"><%= link_to 'a Coder\'s Confessions about being a developing Developer', "/blogs" %></p><br />


 </div>
</div>

</body>
</html>